Number_1 = int(input("Enter Your first Number Here : "))
Number_2 = int(input("Enter Your second Number Here : "))
print("ADDITION",Number_1 + Number_2)
print("SUBSTRACTION",Number_1 - Number_2)
print("MULTIPLY",Number_1 * Number_2)
print("DIVIDE in Float",Number_1 / Number_2)
print("DIVIDE in Int",Number_1 // Number_2)
print("MODULO ",Number_1 % Number_2)
print("POWER(square)",Number_1 ** Number_2)
